var Pessoa = require('../models/clsPessoa')

var homeController = {
    login: function(request, response, next) {
      response.render('login')
    },
    index: function(request, response, next) {
        Pessoa.returnAll(function(pessoas) {
            response.render('index', {
              title: 'Cadastro',
              pessoas: pessoas
            })
          })
    },
    cadastrar_pessoa_service: function(request, response, next) {
        var objPessoa = new Pessoa()
        objPessoa.nome = request.body.nome
        objPessoa.sobrenome = request.body.sobrenome
        objPessoa.cpf = request.body.cpf
        objPessoa.telefone = request.body.telefone
        objPessoa.endereco = request.body.endereco
    
        objPessoa.save(function(){
          response.send({});
        });
      },
      cadastrar_pessoa: function(request, response, next) {
        var objPessoa = new Pessoa()
        objPessoa.nome = request.body.nome
        objPessoa.sobrenome = request.body.sobrenome
        objPessoa.cpf = request.body.cpf
        objPessoa.telefone = request.body.telefone
        objPessoa.endereco = request.body.endereco
    
        objPessoa.save(function(){
          response.redirect("/");
        });
      },
      excluir: function(request, response, next) {
        var objPessoa = new Pessoa()
        objPessoa.cpf = request.query.cpf
        objPessoa.delete(function(){
          response.redirect("/");
        })
      },
      estados: function(request, response, next) {
        var estados = [
          {'SP': 'São Paulo'},
          {'RJ': 'Rio de Janeiro'},
          {'BH': 'Belo Horizonte'},
          {'ES': 'Espirito Santo'}
        ]
        response.send(estados)
      },
      cidades: function(request, response, next) {
        var cidades_estados = [
          {'SP': [
            'São Paulo',
            'Adamantina',
            'Adolfo',
            'Aguai',
            'Aguas da Prata',
            'Aguas de Lindoia',
            'Aguas de Santa Barbara',
            'Aguas de Sao Pedro',
            'Agudos',
            'Alambari',
            'Alfredo Marcondes',
            'Altair',
            'Altinopolis',
            'Alto Alegre',
            'Aluminio',
            'Alvares Florence',
            'Alvares Machado',
            'Alvaro de Carvalho',
            'Alvinlandia',
            'Americana',
            'Americo Brasiliense',
            'Americo de Campos',
            'Amparo',
            'Analandia',
            'Andradina',
            'Angatuba',
            'Anhembi',
            'Anhumas',
            "Aparecida d'Oeste",
            'Aparecida',
            'Apiai',
            'Aracariguama',
            'Aracatuba',
            'Aracoiaba da Serra',
            'Aramina',
            'Arandu',
            'Arapei',
            'Araraquara',
            'Araras',
            'Arco-Iris',
            'Arealva',
            'Areias',
            'Areiopolis',
            'Ariranha',
            'Artur Nogueira',
            'Aruja',
            'Aspasia',
            'Assis',
            'Atibaia',
            'Auriflama',
            'Avai',
            'Avanhandava',
            'Avare',
            'Bady Bassitt',
            'Balbinos',
            'Balsamo',
            'Bananal',
            'Barao de Antonina',
            'Barbosa',
            'Bariri',
            'Barra Bonita',
            'Barra do Chapeu',
            'Barra do Turvo',
            'Barretos',
            'Barrinha',
            'Barueri',
            'Bastos',
            'Batatais',
            'Bauru',
            'Bebedouro',
            'Bento de Abreu',
            'Bernardino de Campos',
            'Bertioga',
            'Bilac',
            'Birigui',
            'Biritiba-Mirim',
            'Boa Esperanca do Sul',
            'Bocaina',
            'Bofete',
            'Boituva',
            'Bom Jesus dos Perdoes',
            'Bom Sucesso de Itarare',
            'Bora',
            'Boraceia',
            'Borborema',
            'Borebi',
            'Botucatu',
            'Braganca Paulista',
            'Brauna',
            'Brejo Alegre',
            'Brodosqui',
            'Brotas',
            'Buri',
            'Buritama',
            'Buritizal',
            'Cabralia Paulista',
            'Cabreuva',
            'Cacapava',
            'Cachoeira Paulista',
            'Caconde',
            'Cafelandia',
            'Caiabu',
            'Caieiras',
            'Caiua',
            'Cajamar',
            'Cajati',
            'Cajobi',
            'Cajuru',
            'Campina do Monte Alegre',
            'Campinas',
            'Campo Limpo Paulista',
            'Campos Novos Paulista',
            'Campos do Jordao',
            'Cananeia',
            'Canas',
            'Candido Mota',
            'Candido Rodrigues',
            'Canitar',
            'Capao Bonito',
            'Capela do Alto',
            'Capivari',
            'Caraguatatuba',
            'Carapicuiba',
            'Cardoso',
            'Casa Branca',
            'Cassia dos Coqueiros',
            'Castilho',
            'Catanduva',
            'Catigua                             ',
            'Cedral                              ',
            'Cerqueira Cesar                     ',
            'Cerquilho                           ',
            'Cesario Lange                       ',
            'Charqueada                          ',
            'Chavantes                           ',
            'Clementina                          ',
            'Colina                              ',
            'Colombia                            ',
            'Conchal                             ',
            'Conchas                             ',
            'Cordeiropolis                       ',
            'Coroados                            ',
            'Coronel Macedo                      ',
            'Corumbatai                          ',
            'Cosmopolis                          ',
            'Cosmorama                           ',
            'Cotia                               ',
            'Cravinhos                           ',
            'Cristais Paulista                   ',
            'Cruzalia                            ',
            'Cruzeiro                            ',
            'Cubatao                             ',
            'Cunha                               ',
            'Descalvado                          ',
            'Diadema                             ',
            'Dirce Reis                          ',
            'Divinolandia                        ',
            'Dobrada                             ',
            'Dois Corregos                       ',
            'Dolcinopolis                        ',
            'Dourado                             ',
            'Dracena                             ',
            'Duartina                            ',
            'Dumont                              ',
            'Echapora                            ',
            'Eldorado                            ',
            'Elias Fausto                        ',
            'Elisiario                           ',
            'Embauba                             ',
            'Embu                                ',
            'Embu-Guacu                          ',
            'Emilianopolis                       ',
            'Engenheiro Coelho                   ',
            'Espirito Santo do Pinhal            ',
            'Espirito Santo do Turvo             ',
            'Estiva Gerbi                        ',
            'Estrela dOeste                     ',
            'Estrela do Norte                    ',
            'Euclides da Cunha Paulista          ',
            'Fartura                             ',
            'Fernando Prestes                    ',
            'Fernandopolis                       ',
            'Fernao                              ',
            'Ferraz de Vasconcelos               ',
            'Flora Rica                          ',
            'Floreal                             ',
            'Florida Paulista                    ',
            'Florinia                            ',
            'Franca                              ',
            'Francisco Morato                    ',
            'Franco da Rocha                     ',
            'Gabriel Monteiro                    ',
            'Galia                               ',
            'Garca                               ',
            'Gastao Vidigal                      ',
            'Gaviao Peixoto                      ',
            'General Salgado                     ',
            'Getulina                            ',
            'Glicerio                            ',
            'Guaicara                            ',
            'Guaimbe                             ',
            'Guaira                              ',
            'Guapiacu                            ',
            'Guapiara                            ',
            'Guara                               ',
            'Guaracai                            ',
            'Guaraci                             ',
            'Guarani dOeste                     ',
            'Guaranta                            ',
            'Guararapes                          ',
            'Guararema                           ',
            'Guaratingueta                       ',
            'Guarei                              ',
            'Guariba                             ',
            'Guaruja                             ',
            'Guarulhos                           ',
            'Guatapara                           ',
            'Guzolandia                          ',
            'Herculandia                         ',
            'Holambra                            ',
            'Hortolandia                         ',
            'Iacanga                             ',
            'Iacri                               ',
            'Iaras                               ',
            'Ibate                               ',
            'Ibira                               ',
            'Ibirarema                           ',
            'Ibitinga                            ',
            'Ibiuna                              ',
            'Icem                                ',
            'Iepe                                ',
            'Igaracu do Tiete                    ',
            'Igarapava                           ',
            'Igarata                             ',
            'Iguape                              ',
            'Ilha Comprida                       ',
            'Ilha Solteira                       ',
            'Ilhabela                            ',
            'Indaiatuba                          ',
            'Indiana                             ',
            'Indiapora                           ',
            'Inubia Paulista                     ',
            'Ipaucu                              ',
            'Ipero                               ',
            'Ipeuna                              ',
            'Ipigua                              ',
            'Iporanga                            ',
            'Ipua                                ',
            'Iracemapolis                        ',
            'Irapua                              ',
            'Irapuru                             ',
            'Itabera                             ',
            'Itai                                ',
            'Itajobi                             ',
            'Itaju                               ',
            'Itanhaem                            ',
            'Itaoca                              ',
            'Itapecerica da Serra                ',
            'Itapetininga                        ',
            'Itapeva                             ',
            'Itapevi                             ',
            'Itapira                             ',
            'Itapirapua Paulista                 ',
            'Itapolis                            ',
            'Itaporanga                          ',
            'Itapui                              ',
            'Itapura                             ',
            'Itaquaquecetuba                     ',
            'Itarare                             ',
            'Itariri                             ',
            'Itatiba                             ',
            'Itatinga                            ',
            'Itirapina                           ',
            'Itirapua                            ',
            'Itobi                               ',
            'Itu                                 ',
            'Itupeva                             ',
            'Ituverava                           ',
            'Jaborandi                           ',
            'Jaboticabal                         ',
            'Jacarei                             ',
            'Jaci                                ',
            'Jacupiranga                         ',
            'Jaguariuna                          ',
            'Jales                               ',
            'Jambeiro                            ',
            'Jandira                             ',
            'Jardinopolis                        ',
            'Jarinu                              ',
            'Jau                                 ',
            'Jeriquara                           ',
            'Joanopolis                          ',
            'Joao Ramalho                        ',
            'Jose Bonifacio                      ',
            'Julio Mesquita                      ',
            'Jumirim                             ',
            'Jundiai                             ',
            'Junqueiropolis                      ',
            'Juquia                              ',
            'Juquitiba                           ',
            'Lagoinha                            ',
            'Laranjal Paulista                   ',
            'Lavinia                             ',
            'Lavrinhas                           ',
            'Leme                                ',
            'Lencois Paulista                    ',
            'Limeira                             ',
            'Lindoia                             ',
            'Lins                                ',
            'Lorena                              ',
            'Lourdes                             ',
            'Louveira                            ',
            'Lucelia                             ',
            'Lucianopolis                        ',
            'Luis Antonio                        ',
            'Luiziania                           ',
            'Lupercio                            ',
            'Lutecia                             ',
            'Macatuba                            ',
            'Macaubal                            ',
            'Macedonia                           ',
            'Magda                               ',
            'Mairinque                           ',
            'Mairipora                           ',
            'Manduri                             ',
            'Maraba Paulista                     ',
            'Maracai                             ',
            'Marapoama                           ',
            'Mariapolis                          ',
            'Marilia                             ',
            'Marinopolis                         ',
            'Martinopolis                        ',
            'Matao                               ',
            'Maua                                ',
            'Mendonca                            ',
            'Meridiano                           ',
            'Mesopolis                           ',
            'Miguelopolis                        ',
            'Mineiros do Tiete                   ',
            'Mira Estrela                        ',
            'Miracatu                            ',
            'Mirandopolis                        ',
            'Mirante do Paranapanema             ',
            'Mirassol                            ',
            'Mirassolandia                       ',
            'Mococa                              ',
            'Mogi Guacu                          ',
            'Moji das Cruzes                     ',
            'Moji-Mirim                          ',
            'Mombuca                             ',
            'Moncoes                             ',
            'Mongagua                            ',
            'Monte Alegre do Sul                 ',
            'Monte Alto                          ',
            'Monte Aprazivel                     ',
            'Monte Azul Paulista                 ',
            'Monte Castelo                       ',
            'Monte Mor                           ',
            'Monteiro Lobato                     ',
            'Morro Agudo                         ',
            'Morungaba                           ',
            'Motuca                              ',
            'Murutinga do Sul                    ',
            'Nantes                              ',
            'Narandiba                           ',
            'Natividade da Serra                 ',
            'Nazare Paulista                     ',
            'Neves Paulista                      ',
            'Nhandeara                           ',
            'Nipoa                               ',
            'Nova Alianca                        ',
            'Nova Campina                        ',
            'Nova Canaa Paulista                 ',
            'Nova Castilho                       ',
            'Nova Europa                         ',
            'Nova Granada                        ',
            'Nova Guataporanga                   ',
            'Nova Independencia                  ',
            'Nova Luzitania                      ',
            'Nova Odessa                         ',
            'Novais                              ',
            'Novo Horizonte                      ',
            'Nuporanga                           ',
            'Ocaucu                              ',
            'Oleo                                ',
            'Olimpia                             ',
            'Onda Verde                          ',
            'Oriente                             ',
            'Orindiuva                           ',
            'Orlandia                            ',
            'Osasco                              ',
            'Oscar Bressane                      ',
            'Osvaldo Cruz                        ',
            'Ourinhos                            ',
            'Ouro Verde                          ',
            'Ouroeste                            ',
            'Pacaembu                            ',
            'Palestina                           ',
            'Palmares Paulista                   ',
            'Palmeira dOeste                    ',
            'Palmital                            ',
            'Panorama                            ',
            'Paraguacu Paulista                  ',
            'Paraibuna                           ',
            'Paraiso                             ',
            'Paranapanema                        ',
            'Paranapua                           ',
            'Parapua                             ',
            'Pardinho                            ',
            'Pariquera-Acu                       ',
            'Parisi                              ',
            'Patrocinio Paulista                 ',
            'Pauliceia                           ',
            'Paulinia                            ',
            'Paulistania                         ',
            'Paulo de Faria                      ',
            'Pederneiras                         ',
            'Pedra Bela                          ',
            'Pedranopolis                        ',
            'Pedregulho                          ',
            'Pedreira                            ',
            'Pedrinhas Paulista                  ',
            'Pedro de Toledo                     ',
            'Penapolis                           ',
            'Pereira Barreto                     ',
            'Pereiras                            ',
            'Peruibe                             ',
            'Piacatu                             ',
            'Piedade                             ',
            'Pilar do Sul                        ',
            'Pindamonhangaba                     ',
            'Pindorama                           ',
            'Pinhalzinho                         ',
            'Piquerobi                           ',
            'Piquete                             ',
            'Piracaia                            ',
            'Piracicaba                          ',
            'Piraju                              ',
            'Pirajui                             ',
            'Pirangi                             ',
            'Pirapora do Bom Jesus               ',
            'Pirapozinho                         ',
            'Pirassununga                        ',
            'Piratininga                         ',
            'Pitangueiras                        ',
            'Planalto                            ',
            'Platina                             ',
            'Poa                                 ',
            'Poloni                              ',
            'Pompeia                             ',
            'Pongai                              ',
            'Pontal                              ',
            'Pontalinda                          ',
            'Pontes Gestal                       ',
            'Populina                            ',
            'Porangaba                           ',
            'Porto Feliz                         ',
            'Porto Ferreira                      ',
            'Potim                               ',
            'Potirendaba                         ',
            'Pracinha                            ',
            'Pradopolis                          ',
            'Praia Grande                        ',
            'Pratania                            ',
            'Presidente Alves                    ',
            'Presidente Bernardes                ',
            'Presidente Epitacio                 ',
            'Presidente Prudente                 ',
            'Presidente Venceslau                ',
            'Promissao                           ',
            'Quadra                              ',
            'Quata                               ',
            'Queiroz                             ',
            'Queluz                              ',
            'Quintana                            ',
            'Rafard                              ',
            'Rancharia                           ',
            'Redencao da Serra                   ',
            'Regente Feijo                       ',
            'Reginopolis                         ',
            'Registro                            ',
            'Restinga                            ',
            'Ribeira                             ',
            'Ribeirao Bonito                     ',
            'Ribeirao Branco                     ',
            'Ribeirao Corrente                   ',
            'Ribeirao Grande                     ',
            'Ribeirao Pires                      ',
            'Ribeirao Preto                      ',
            'Ribeirao do Sul                     ',
            'Ribeirao dos Indios                 ',
            'Rifaina                             ',
            'Rincao                              ',
            'Rinopolis                           ',
            'Rio Claro                           ',
            'Rio Grande da Serra                 ',
            'Rio das Pedras                      ',
            'Riolandia                           ',
            'Riversul                            ',
            'Rosana                              ',
            'Roseira                             ',
            'Rubiacea                            ',
            'Rubineia                            ',
            'Sabino                              ',
            'Sagres                              ',
            'Sales Oliveira                      ',
            'Sales                               ',
            'Salesopolis                         ',
            'Salmourao                           ',
            'Saltinho                            ',
            'Salto Grande                        ',
            'Salto de Pirapora                   ',
            'Salto                               ',
            'Sandovalina                         ',
            'Santa Adelia                        ',
            'Santa Albertina                     ',
            'Santa Barbara dOeste               ',
            'Santa Branca                        ',
            'Santa Clara dOeste                 ',
            'Santa Cruz da Conceicao             ',
            'Santa Cruz da Esperanca             ',
            'Santa Cruz das Palmeiras            ',
            'Santa Cruz do Rio Pardo             ',
            'Santa Ernestina                     ',
            'Santa Fe do Sul                     ',
            'Santa Gertrudes                     ',
            'Santa Isabel                        ',
            'Santa Lucia                         ',
            'Santa Maria da Serra                ',
            'Santa Mercedes                      ',
            'Santa Rita dOeste                  ',
            'Santa Rita do Passa Quatro          ',
            'Santa Rosa de Viterbo               ',
            'Santa Salete                        ',
            'Santana da Ponte Pensa              ',
            'Santana de Parnaiba                 ',
            'Santo Anastacio                     ',
            'Santo Andre                         ',
            'Santo Antonio da Alegria            ',
            'Santo Antonio de Posse              ',
            'Santo Antonio do Aracangua          ',
            'Santo Antonio do Jardim             ',
            'Santo Antonio do Pinhal             ',
            'Santo Expedito                      ',
            'Santopolis do Aguapei               ',
            'Santos                              ',
            'Sao Bento do Sapucai                ',
            'Sao Bernardo do Campo               ',
            'Sao Caetano do Sul                  ',
            'Sao Carlos                          ',
            'Sao Francisco                       ',
            'Sao Joao da Boa Vista               ',
            'Sao Joao das Duas Pontes            ',
            'Sao Joao de Iracema                 ',
            'Sao Joao do Pau dAlho              ',
            'Sao Joaquim da Barra                ',
            'Sao Jose da Bela Vista              ',
            'Sao Jose do Barreiro                ',
            'Sao Jose do Rio Pardo               ',
            'Sao Jose do Rio Preto               ',
            'Sao Jose dos Campos                 ',
            'Sao Lourenco da Serra               ',
            'Sao Luis do Paraitinga              ',
            'Sao Manuel                          ',
            'Sao Miguel Arcanjo                  ',
            'Sao Paulo                           ',
            'Sao Pedro do Turvo                  ',
            'Sao Pedro                           ',
            'Sao Roque                           ',
            'Sao Sebastiao da Grama              ',
            'Sao Sebastiao                       ',
            'Sao Simao                           ',
            'Sao Vicente                         ',
            'Sarapui                             ',
            'Sarutaia                            ',
            'Sebastianopolis do Sul              ',
            'Serra Azul                          ',
            'Serra Negra                         ',
            'Serrana                             ',
            'Sertaozinho                         ',
            'Sete Barras                         ',
            'Severinia                           ',
            'Silveiras                           ',
            'Socorro                             ',
            'Sorocaba                            ',
            'Sud Mennucci                        ',
            'Sumare                              ',
            'Suzanapolis                         ',
            'Suzano                              ',
            'Tabapua                             ',
            'Tabatinga                           ',
            'Taboao da Serra                     ',
            'Taciba                              ',
            'Taguai                              ',
            'Taiacu                              ',
            'Taiuva                              ',
            'Tambau                              ',
            'Tanabi                              ',
            'Tapirai                             ',
            'Tapiratiba                          ',
            'Taquaral                            ',
            'Taquaritinga                        ',
            'Taquarituba                         ',
            'Taquarivai                          ',
            'Tarabai                             ',
            'Taruma                              ',
            'Tatui                               ',
            'Taubate                             ',
            'Tejupa                              ',
            'Teodoro Sampaio                     ',
            'Terra Roxa                          ',
            'Tiete                               ',
            'Timburi                             ',
            'Torre de Pedra                      ',
            'Torrinha                            ',
            'Trabiju                             ',
            'Tremembe                            ',
            'Tres Fronteiras                     ',
            'Tuiuti                              ',
            'Tupa                                ',
            'Tupi Paulista                       ',
            'Turiuba                             ',
            'Turmalina                           ',
            'Ubarana                             ',
            'Ubatuba                             ',
            'Ubirajara                           ',
            'Uchoa                               ',
            'Uniao Paulista                      ',
            'Urania                              ',
            'Uru                                 ',
            'Urupes                              ',
            'Valentim Gentil                     ',
            'Valinhos                            ',
            'Valparaiso                          ',
            'Vargem Grande Paulista              ',
            'Vargem Grande do Sul                ',
            'Vargem                              ',
            'Varzea Paulista                     ',
            'Vera Cruz                           ',
            'Vinhedo                             ',
            'Viradouro                           ',
            'Vista Alegre do Alto                ',
            'Vitoria Brasil                      ',
            'Votorantim                          ',
            'Votuporanga                         ',
            'Zacarias                            '
          ]},
          {'RJ': ['Rio de Janeiro']},
          {'BH': ['Belo Horizonte']},
          {'ES': ['Espirito Santo']}
        ]
        if(request.query.estado != undefined && request.query.estado != ''){
          var cidades = []
          var estadoRequest = request.query.estado.toUpperCase()
          console.log('Estado selecionado: ' + estadoRequest)
          for(var i=0; i < cidades_estados.length; i++){
            if(cidades_estados[i][estadoRequest]){
              cidades = cidades_estados[i][estadoRequest]
              i = cidades_estados.length + 1
            }
          }
          if(cidades == []){
            cidades = cidades_estados
          }
          response.send(cidades)
        }
        else{
          response.send([])
        }
      }
}

module.exports = homeController